# Generated by Django 4.1.3 on 2023-06-14 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_section_sec_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sec_file',
            field=models.FileField(default=None, upload_to='files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'rar', 'zip', 'MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
