# Generated by Django 4.1.3 on 2023-06-11 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_en_title_course_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('section_type', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['-created_at'], name='courses_sec_created_a6de8e_idx'),
        ),
    ]
