# Generated by Django 4.1.3 on 2023-06-14 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_type',
        ),
        migrations.AddField(
            model_name='section',
            name='sec_file',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'rar', 'zip', 'MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='section',
            name='sec_type',
            field=models.CharField(blank=True, choices=[('PD', 'Pdf'), ('DC', 'Doc'), ('VD', 'Video'), ('RR', 'Rar'), ('ZP', 'Zip')], max_length=2, null=True),
        ),
    ]
