# Generated by Django 4.2.2 on 2023-06-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_managers_alter_section_sec_file'),
        ('courses', '0010_alter_section_sec_file'),
    ]

    operations = [
    ]
